export enum ItemType {
  STICK = 'STICK',
  WIRE = 'WIRE',
  UMBRELLA = 'UMBRELLA',
  CAMPFIRE = 'CAMPFIRE',
  NUKE = 'NUKE',
  NAPALM = 'NAPALM',
  REVELATION = 'REVELATION',
  BIRD = 'BIRD',
  SILENCER = 'SILENCER',
  SHEARS = 'SHEARS',
  BEARTRAP = 'BEARTRAP'
}