export enum StatusEffectType {
    STICK='STICK',
    TRAPPED='TRAPPED',
    SILENCER='SILENCER',
    NUKE_CHARGING='NUKE_CHARGING',
    NUKE_READY='NUKE_READY',
    NAPALM_CHARGING='NAPALM_CHARGING',
    NAPALM_READY='NAPALM_READY'
}
